{{- if (index .Values "pozos-api" "persistence" "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pozos-website.fullname" . }}-backup
  labels:
    {{- include "pozos-website.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
        - name: backup
          image: busybox 
          command: ["/bin/sh", "-c"]
          args: ["cp /data/student_age.json /backup/"]
          volumeMounts:
            - name: pozos-api-data
              mountPath: /data
            - name: backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: pozos-api-data
          persistentVolumeClaim:
            claimName: {{ index .Values "pozos-api" "fullnameOverride" }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ index .Values "pozos-api" "fullnameOverride" }}-backup-{{ sub .Release.Revision 1 }}-{{ .Release.Name }}
{{- end }}
