apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pozos-website.fullname" . }}-secret
  labels: {{- include "pozos-website.labels" . | nindent 4 }} 
type: Opaque
data:
  username: {{ .Values.apiSecret.username | b64enc | quote }}
  password: {{ .Values.apiSecret.password | b64enc | quote }}
