apiVersion: v1
kind: Service
metadata:
  name: {{ include "pozos-website.fullname" . }}
  labels:
    {{- include "pozos-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "pozos-website.selectorLabels" . | nindent 4 }}
