# permissions for end users to view pozoswebsites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pozoswebsite-viewer-role
rules:
- apiGroups:
  - charts.pozos.com
  resources:
  - pozoswebsites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.pozos.com
  resources:
  - pozoswebsites/status
  verbs:
  - get
