apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pozos-website.fullname" . }}-config 
data:
  # this syntax can be found here https://helm.sh/docs/chart_template_guide/accessing_files/
  {{- $files := .Files }}
  {{- range tuple "index.php" }}
  {{ . }}: |-
    <!-- Fix issue : did not find expected key -->
    {{ $files.Get . | indent 4 }}
  {{- end }}
